export default {
  opportunities: [
    {
      id: 1,
      title: 'A/V Technician',
      description: 'We are seeking a full-time experienced A/V technician to join our production team. Ideal candidates will have extensive hotel A/V experience, live broadcasting experience and familiarity with networked A/V. Candidates must be effective communicators and have experience in professional working environments. To be considered for this position, applicants must submit a resume and a cover letter.',
      start: '03-20-2020',
      duration: '20 weeks',
      commitment: '5 hours',
      edlevel: 'High School',
      experience: 'Audio Visual: 2 years (Preferred)',
      remote: 'No.',
      posted: '02-15-2020',
      organization: 'Colorado Bar Association CLE',
      location: 'Denver, CO 80203'
    },
    {
      id: 2,
      title: 'Website Specialist',
      description: 'We are currently seeking a Denver Metro-based Website Specialist to support the media and communications team at the BACB. This person will focus primarily on supporting the corporate websites and eLearning platforms. Candidates should enjoy a fast-paced environment; take pride in being detail and deadline-oriented; have the confidence to switch between self-directed work and collaborative projects seamlessly. Must have excellent communication skills and work ethic. The BACB® is a nonprofit 501(c)(3) corporation established in 1998 to meet professional credentialing needs identified by behavior analysts, governments, and consumers of behavior analysis services. We are located in Littleton, CO with beautiful views of the adjacent mountains.',
      start: '04-16-2020',
      duration: '40 weeks',
      commitment: '5 hours',
      edlevel: 'Bachelors',
      experience: '2+ years of direct experience with Content Management Systems',
      remote: 'Yes.',
      posted: '01-26-2020',
      organization: 'Behavior Analyst Certification Board',
      location: 'Littleton, CO 80127'
    },
    {
      id: 3,
      title: 'Construction Site Manager',
      description: 'Primary Role: The Construction Site Manager coordinates the construction of safe, decent, affordable housing by: Overseeing the construction process including but not limited to rehab, new construction and repair work on all BSHfH projects.Supervising and leading on-site construction, including the construction site supervisors and crew leaders, as well as construction volunteers. Creating a positive and encouraging work atmosphere. Ensuring that safety guidelines are followed on-site and that adequate training is provided to construction team and daily volunteers. Being responsible for seeing that homes are built in accordance with applicable building codes. Being skilled in detailed techniques and principles of construction, construction scheduling, procurement, budgeting, warranty program and continuous improvement.',
      start: '07-20-2020',
      duration: 'No end date',
      commitment: '40 hours',
      edlevel: 'High School',
      experience: 'Experience managing volunteer construction programs.',
      license: '',
      remote: 'No.',
      posted: '03-15-2020',
      organization: 'Blue Spruce Habitat for Humanity',
      location: 'Evergreen, CO'
    },
    {
      id: 4,
      title: 'Volunteer & Donations Coordinator',
      description: 'The Volunteer and Donations Coordinator will serve as a main point of contact for managing external interests in the IRC Denver office. This includes managing relationships with volunteers, faith based organizations, and corporate partners. The position is also responsible for providing community outreach regarding the work and volunteer needs of the office, assisting with communications and media, overseeing donations, and recruiting and supporting volunteers to support in the delivery of the office’s programs and services. The Volunteer and Donations Coordinator is responsible for designing effective volunteer opportunities to support core IRC programming, and for the procurement, management, delivery of and attaining goals of ‘in-kind’ contributions. This position reports to the Colorado Advocacy Officer.',
      start: 'Right Away',
      duration: 'Long-term',
      commitment: '15 hours',
      edlevel: 'Bachelors',
      experience: 'Undergraduate degree in communications',
      remote: 'No.',
      posted: '02-15-2020',
      organization: 'International Rescue Committee',
      location: 'Denver, CO 80228'
    },
    {
      id: 5,
      title: 'Executive Assistant to Non Profit Leadership',
      description: 'The Executive Office of The Public Interest Network seeks an Administrative Assistant. We are looking for a smart, committed, and detail-oriented candidate to join our team to assist the President and Vice Presidents in managing the daily operations of the organization and in long-term planning. The Public Interest Network is home to more than 15 organizations—including PIRG, Environment America, Green Corps, and the National Environmental Law Center—that share a vision of a better world, a set of core values, and a strategic approach to change. Our mission is to tackle some of the big questions facing our country. How do we make sure the next generation has clean air, clean water and a livable climate? How do we transform our energy and transportation systems to meet the needs of today, not the last century? How do we grow and raise our food in ways that leave both people and our environment healthier? Our country needs smart solutions to these and other problems, and our researchers and advocates have come up with dozens of them. But having good ideas isn’t enough. We have to find ways to cut through all the noise in today’s politics and win over decision makers, opinion leaders and the public.   We’re transpartisan. We value dialogue over polarization. We invest in people and strategies that deliver results, including advocacy, lobbying, campaigning, litigation, policy research and grassroots organizing. Over the past 45 years, our coordinated approach has won hundreds of victories. Because of the laws and other policies we’ve won, people are buying healthier and safer products, getting more of our energy from the sun and the wind, and drinking cleaner water and breathing cleaner air. In order to achieve these results, the groups in The Public Interest Network need a strong backup staff to provide the resources, guidance, and infrastructure it takes to make progress on these issues.',
      start: '09-10-2020',
      duration: '10 weeks',
      commitment: '50 hours',
      edlevel: 'High School',
      experience: 'Audio Visual: 2 years (Preferred)',
      remote: 'No.',
      posted: '12-15-2019',
      organization: 'The Public Interest Network',
      location: 'Denver, CO'
    },
    {
      id: 6,
      title: 'Area Director, Western Region - Rocky Mountains & Washington',
      description: 'AVID Center is currently looking for two experienced, motivated, and influential educational leaders to join their Western Region team in the role of Area Director. This high-level position offers the ability to make a huge impact on schools, students, and families in the communities it serves. Area Directors provide overarching support to AVID Program Managers, who work directly with AVID district leadership, site/school leaders, and other key stakeholders to implement, manage, and grow their AVID College and Career Readiness System. Area Directors must have a thorough understanding of the ever-changing educational landscape, including the nuances of each state and the districts they serve, to ensure the best solutions and systems of support. Area Directors need to be comfortable working with stakeholders at all levels, from communicating with a principal on a school campus, to meeting with superintendents, to presenting information to state legislators and partnering with other organizations for funding opportunities. Their ability to easily transition to accommodate a variety of audiences is key. At a time when the resources of teachers, schools, and districts are more stretched than ever, AVID is dedicated to providing a solution for support and success, and the Area Directors are at the forefront of that mission.',
      start: 'ASAP',
      duration: 'Indefinite',
      commitment: '2 hours',
      edlevel: 'High School',
      experience: 'Experience with the AVID College and Career Readiness System',
      license: '',
      remote: 'Yes.',
      posted: '02-17-2020',
      organization: 'AVID CENTER STAFF',
      location: 'Englewood, CO 80111'
    },
    {
      id: 7,
      title: 'Senior Events Manager',
      description: 'Reporting to the Director of Events, the Senior Events Manager is responsible for overseeing the promotion and logistical execution of global events. This includes but is not limited to: managing vendors, managing onsite experience design, overseeing A/V production, and managing registration. Additionally this role will provide support for other global, regional, and community events. Successful candidates will have managed and coordinated events for international trade groups in the technology sector.',
      start: 'Today',
      duration: '6 weeks',
      commitment: '10 hours',
      edlevel: 'Masters',
      experience: 'Events Management: 3 years (Preferred)',
      remote: 'Yes.',
      posted: '03-20-2020',
      organization: 'OWASP Foundation',
      location: 'Denver, CO'
    },
    {
      id: 8,
      title: 'Patient Access Registration Specialist',
      description: 'Register patients. Confirm, enter, and/or update all required demographic data on patient and guarantor on registration system. Avoid overlays and duplicate patient medical records. Follow procedures when identifying a patient and applying the patient identification bracelet. Register patients during downtime following downtime procedures and enter data into registration system immediately upon system availability. Obtain and explain copies of insurance card(s), forms of ID, and signature(s) on all required forms. Verify information on appropriate accounts to determine insurance coordination of benefits, pre-certification/prior-authorization if not verified by PASC. Complete the Medicare Secondary Payer (MSP) questionnaire when applicable. Verify insurance to determine coordination of benefits and obtain authorization and/or referrals as required. Screen for and process non-covered services and waiver of liability (ABN) through automated screening at time of service.',
      start: '05-20-2020',
      duration: '15 weeks',
      commitment: '5 hours',
      edlevel: 'High School',
      experience: 'At least one (1) year of experience in the hospitality or service industry, preferred',
      remote: 'No.',
      posted: '02-15-2020',
      organization: 'Lutheran Medical Center',
      location: 'Wheat Ridge, CO 80034'
    },
    {
      id: 9,
      title: 'Administrative Assistant',
      description: 'The Administrative Assistant is responsible for ensuring smooth office operations and is responsible for administrative functions including data entry, filing, reporting and record keeping systems and providing administrative support to the Division.',
      start: 'Now',
      duration: 'Indefinite',
      commitment: '10 hours',
      edlevel: 'Associates',
      experience: 'Keyboarding skills of 50 W.P.M.',
      remote: 'No.',
      posted: '01-22-2020',
      organization: 'Volunteers of America Inc',
      location: 'Denver, CO 80205'
    },
    {
      id: 10,
      title: 'Operations Manager',
      description: 'This is a full-time administrative exempt position requiring a Bachelor’s degree and reporting to the Assistant Principal of Operations (APO). This individual manages the execution of all school-based operational systems. The Operations Manager coordinates with staff, vendors and regional team members to ensure execution of clear operational systems focused on fulfilling the needs of students, families, staff and school community stakeholders.',
      start: '03-20-2020',
      duration: '5 weeks',
      commitment: '5 hours',
      edlevel: 'High School',
      experience: 'Audio Visual: 2 years (Preferred)',
      license: '',
      remote: 'No.',
      posted: '03-01-2020',
      organization: 'KIPP Foundation',
      location: 'Denver, CO 80203'
    },
    {
      id: 11,
      title: 'Acquisition Coordinator',
      description: 'Free Speech TV (FSTV) is a national, nonprofit, independent news network whose mission is to empower an informed and active citizenry to build a more just, equitable world. Decidedly mission-driven and goal-oriented, FSTV’s staff, board, volunteers and donors are passionate and committed to advancing progressive social change. These are exciting and challenging times for independent media. Operating in its 25th year, FSTV is fiercely committed to reporting news ignored or even censored by commercial networks. Our array of programs provides viewers with unfiltered news and analysis, amplifies underrepresented voices, and promotes those working on the front lines of social, economic and environmental justice.',
      start: '03-20-2020',
      duration: 'Indefinite',
      commitment: '10 hours',
      edlevel: 'Bachelors',
      experience: 'Passion and historical knowledge of social justice movements, protest and documentary films',
      remote: 'Yes.',
      posted: '02-15-2020',
      organization: 'Free Speech TV',
      location: 'Denver, CO 80205'
    },
    {
      id: 12,
      title: 'ScrumMaster',
      description: 'As a member of this team, you’ll work cross-functionally, contributing your unique skill set to develop big solutions to best serve your community. You’ll also self-manage and self-organize to plan and execute your work based on the team’s backlog. Most importantly, you will be supported to be the best version of yourself, with a dedicated professional development budget and support from your peers to achieve your personal and professional goals.',
      start: '03-20-2020',
      duration: '20 weeks',
      commitment: '40 hours',
      edlevel: 'Bachelors',
      experience: 'Minimum of 8 year’s experience in a related role',
      license: '',
      remote: 'Yes.',
      posted: '09-15-2019',
      organization: 'Scrum Alliance, Inc.',
      location: 'Westminster, CO 80021'
    },
    {
      id: 13,
      title: 'Family Coach',
      description: 'Savio House, a private, non-profit agency is seeking a full-time Family Coach. The ideal candidate is self-motivated, dependable, and is comfortable working with minimal supervision, under the direction of the Child Protection Coordinator. A successful candidate will provide coaching to families to prevent out-of-home placement or prepare the family and child for successful reunification or emancipation.',
      start: 'ASAP',
      duration: '4 weeks',
      commitment: '5 hours',
      edlevel: 'Bachelors',
      remote: 'No.',
      posted: '03-15-2020',
      organization: 'Savio House',
      location: 'Denver, CO 80219'
    }
  ]
}